
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ana", email = "Anaclara.hahn1@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
    "black>=23.7.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
